# Writes db_build_provenance.h with the source revision this image was built
# from. Run on every build (cmake -P) and rewrites the header only when its
# content changes, so an incremental build never reports a stale revision and
# an unchanged revision does not force a recompile.
#
# Reports only what git can establish: without git, outside a work tree, or if
# a query fails, the SHA is empty and the tree state is "unknown".
#
# Inputs: -DSOURCE_DIR=<project dir> -DOUTPUT=<header path>

set(git_sha "")
set(source_tree "unknown")
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    # Containerized CI checkouts are often owned by another user.
    set(git ${GIT_EXECUTABLE} -c safe.directory=${SOURCE_DIR} -C ${SOURCE_DIR})
    execute_process(COMMAND ${git} rev-parse --verify HEAD
                    OUTPUT_VARIABLE head RESULT_VARIABLE head_result
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(head_result EQUAL 0 AND head MATCHES "^[0-9a-f]+$")
        set(git_sha "${head}")
        # Tracked changes and untracked, non-ignored files both count as dirty.
        execute_process(COMMAND ${git} status --porcelain
                        OUTPUT_VARIABLE status RESULT_VARIABLE status_result ERROR_QUIET)
        if(status_result EQUAL 0)
            if(status STREQUAL "")
                set(source_tree "clean")
            else()
                set(source_tree "dirty")
            endif()
        endif()
    endif()
endif()

set(content "// Generated by build_provenance.cmake. Do not edit.\n#pragma once\n#define DB_BUILD_GIT_SHA \"${git_sha}\"\n#define DB_BUILD_SOURCE_TREE \"${source_tree}\"\n")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
else()
    set(previous "")
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
